from . import AllChem as AllChem
from . import Crippen as Crippen
from . import Descriptors as Descriptors
from . import Draw as Draw
from . import Lipinski as Lipinski
from . import rdFingerprintGenerator as rdFingerprintGenerator
from . import rdMolDescriptors as rdMolDescriptors

class Mol:
    def GetNumHeavyAtoms(self) -> int: ...

def AddHs(mol: Mol) -> Mol: ...
def MolFromSmiles(smiles: str) -> Mol | None: ...
def MolToMolBlock(mol: Mol) -> str: ...
def MolToSmiles(mol: Mol, canonical: bool = True) -> str: ...
