from . import Mol

class MolDraw2DSVG:
    def __init__(self, width: int, height: int) -> None: ...
    def DrawMolecule(self, mol: Mol) -> None: ...
    def FinishDrawing(self) -> None: ...
    def GetDrawingText(self) -> str: ...
