/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/candidate-sets/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Candidate Set */
        get: operations["get_demo_candidate_set_api_candidate_sets_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/conformer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Conformer */
        get: operations["get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Neighbors */
        get: operations["get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Projection */
        get: operations["get_demo_projection_api_candidate_sets_demo_projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Evidence Bundle */
        post: operations["import_evidence_bundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Summary */
        get: operations["get_run_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_evidence_bundle */
        Body_import_evidence_bundle: {
            /**
             * Bundle
             * @description Portable Molecule Atlas evidence bundle ZIP
             */
            bundle: string;
        };
        /** CandidateSet */
        CandidateSet: {
            /** Candidates */
            candidates: (components["schemas"]["ValidCandidate"] | components["schemas"]["InvalidCandidate"])[];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ConformerResponse */
        ConformerResponse: {
            /** Candidate Id */
            candidate_id: string;
            /** Mol Block */
            mol_block: string;
        };
        /** DescriptorSet */
        DescriptorSet: {
            /** Fraction Csp3 */
            fraction_csp3: number;
            /** Hbond Acceptors */
            hbond_acceptors: number;
            /** Hbond Donors */
            hbond_donors: number;
            /** Heavy Atom Count */
            heavy_atom_count: number;
            /** Logp */
            logp: number;
            /** Molecular Weight */
            molecular_weight: number;
            /** Murcko Scaffold */
            murcko_scaffold: string | null;
            /** Ring Count */
            ring_count: number;
            /** Rotatable Bonds */
            rotatable_bonds: number;
            /** Tpsa */
            tpsa: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** GetRunSummaryOutput */
        GetRunSummaryOutput: {
            /**
             * Capability Id
             * @default get_run_summary
             * @constant
             */
            capability_id: "get_run_summary";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            run: components["schemas"]["RunSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ImportEvidenceBundleOutput */
        ImportEvidenceBundleOutput: {
            /**
             * Capability Id
             * @default import_evidence_bundle
             * @constant
             */
            capability_id: "import_evidence_bundle";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Idempotency Replayed */
            idempotency_replayed: boolean;
            run: components["schemas"]["RunSummary"];
        };
        /** InvalidCandidate */
        InvalidCandidate: {
            /** Canonical Smiles */
            canonical_smiles?: null;
            /** Descriptors */
            descriptors?: null;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default false
             * @constant
             */
            is_valid: false;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "invalid";
            /** Structure Svg */
            structure_svg?: null;
            /** Target */
            target?: string | null;
            /** Triage Flags */
            triage_flags?: null;
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        JsonValue: unknown;
        /** ManifestWarning */
        ManifestWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /** MethodSummary */
        MethodSummary: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            /** Checkpoint Id */
            checkpoint_id: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256: string | null;
            /** Command */
            command: string[];
            /** Container Digest */
            container_digest: string | null;
            /** Container Image */
            container_image: string | null;
            /** Method Id */
            method_id: string;
            /** Random Seeds */
            random_seeds: number[];
            /** Source Commit */
            source_commit: string | null;
            /** Upstream Tool */
            upstream_tool: string | null;
            /** Upstream Version */
            upstream_version: string | null;
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RunFailure */
        RunFailure: {
            /** Category */
            category: string;
            /** Details */
            details: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Exit Code */
            exit_code?: number | null;
            /** Message */
            message: string;
            /** Stage */
            stage?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Artifact Count */
            artifact_count: number;
            /** Expected Outputs */
            expected_outputs: string[];
            failure: components["schemas"]["RunFailure"] | null;
            /** Finished At */
            finished_at: string | null;
            method: components["schemas"]["MethodSummary"];
            /** Missing Outputs */
            missing_outputs: string[];
            /** Prediction Count */
            prediction_count: number;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "succeeded" | "failed" | "partial" | "cancelled" | "unknown";
            validation_counts: components["schemas"]["ValidationCounts"];
            /** Warnings */
            warnings: components["schemas"]["ManifestWarning"][];
        };
        /** SimilarityNeighbor */
        SimilarityNeighbor: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** Similarity */
            similarity: number;
        };
        /** TriageFlags */
        TriageFlags: {
            /** Lipinski Notes */
            lipinski_notes: string[];
            /** Lipinski Violations */
            lipinski_violations: number;
            /** Veber Notes */
            veber_notes: string[];
            /** Veber Violations */
            veber_violations: number;
        };
        /** ValidCandidate */
        ValidCandidate: {
            /** Canonical Smiles */
            canonical_smiles: string;
            descriptors: components["schemas"]["DescriptorSet"];
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default true
             * @constant
             */
            is_valid: true;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "valid";
            /** Structure Svg */
            structure_svg: string;
            /** Target */
            target?: string | null;
            triage_flags: components["schemas"]["TriageFlags"];
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        /** ValidationCounts */
        ValidationCounts: {
            /** Error Count */
            error_count: number;
            /** Fail Count */
            fail_count: number;
            /** Pass Count */
            pass_count: number;
            /** Unavailable Count */
            unavailable_count: number;
            /** Warning Count */
            warning_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationNote */
        ValidationNote: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_candidate_set_api_candidate_sets_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSet"];
                };
            };
        };
    };
    get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConformerResponse"];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conformer cannot be generated */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stored candidate data is inconsistent */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityNeighbor"][];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_projection_api_candidate_sets_demo_projection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionPoint"][];
                };
            };
        };
    };
    import_evidence_bundle: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Correlation-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_evidence_bundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportEvidenceBundleOutput"];
                };
            };
            /** @description Unsafe or invalid evidence bundle */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Import conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Evidence bundle limit exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_summary: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRunSummaryOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
