/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/candidate-sets/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Candidate Set */
        get: operations["get_demo_candidate_set_api_candidate_sets_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/conformer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Conformer */
        get: operations["get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Neighbors */
        get: operations["get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Projection */
        get: operations["get_demo_projection_api_candidate_sets_demo_projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateSet */
        CandidateSet: {
            /** Candidates */
            candidates: (components["schemas"]["ValidCandidate"] | components["schemas"]["InvalidCandidate"])[];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ConformerResponse */
        ConformerResponse: {
            /** Candidate Id */
            candidate_id: string;
            /** Mol Block */
            mol_block: string;
        };
        /** DescriptorSet */
        DescriptorSet: {
            /** Fraction Csp3 */
            fraction_csp3: number;
            /** Hbond Acceptors */
            hbond_acceptors: number;
            /** Hbond Donors */
            hbond_donors: number;
            /** Heavy Atom Count */
            heavy_atom_count: number;
            /** Logp */
            logp: number;
            /** Molecular Weight */
            molecular_weight: number;
            /** Murcko Scaffold */
            murcko_scaffold: string | null;
            /** Ring Count */
            ring_count: number;
            /** Rotatable Bonds */
            rotatable_bonds: number;
            /** Tpsa */
            tpsa: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** InvalidCandidate */
        InvalidCandidate: {
            /** Canonical Smiles */
            canonical_smiles?: null;
            /** Descriptors */
            descriptors?: null;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default false
             * @constant
             */
            is_valid: false;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "invalid";
            /** Structure Svg */
            structure_svg?: null;
            /** Target */
            target?: string | null;
            /** Triage Flags */
            triage_flags?: null;
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** SimilarityNeighbor */
        SimilarityNeighbor: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** Similarity */
            similarity: number;
        };
        /** TriageFlags */
        TriageFlags: {
            /** Lipinski Notes */
            lipinski_notes: string[];
            /** Lipinski Violations */
            lipinski_violations: number;
            /** Veber Notes */
            veber_notes: string[];
            /** Veber Violations */
            veber_violations: number;
        };
        /** ValidCandidate */
        ValidCandidate: {
            /** Canonical Smiles */
            canonical_smiles: string;
            descriptors: components["schemas"]["DescriptorSet"];
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default true
             * @constant
             */
            is_valid: true;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "valid";
            /** Structure Svg */
            structure_svg: string;
            /** Target */
            target?: string | null;
            triage_flags: components["schemas"]["TriageFlags"];
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationNote */
        ValidationNote: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_candidate_set_api_candidate_sets_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSet"];
                };
            };
        };
    };
    get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConformerResponse"];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conformer cannot be generated */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stored candidate data is inconsistent */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityNeighbor"][];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_projection_api_candidate_sets_demo_projection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionPoint"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
