/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/candidate-sets/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Candidate Set */
        get: operations["get_demo_candidate_set_api_candidate_sets_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/conformer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Conformer */
        get: operations["get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/candidates/{candidate_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Neighbors */
        get: operations["get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-sets/demo/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Projection */
        get: operations["get_demo_projection_api_candidate_sets_demo_projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Candidates */
        post: operations["compare_candidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Evidence Bundle */
        post: operations["import_evidence_bundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Runs */
        get: operations["list_evidence_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Summary */
        get: operations["get_run_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}/artifact-validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate Evidence Artifacts */
        get: operations["validate_evidence_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Available Artifacts */
        get: operations["list_available_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}/candidates/{candidate_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Evidence */
        get: operations["get_candidate_evidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate Evidence Report */
        get: operations["generate_evidence_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactCheck */
        ArtifactCheck: {
            /** Actual Sha256 */
            actual_sha256?: string | null;
            /** Actual Size Bytes */
            actual_size_bytes?: number | null;
            /** Artifact Id */
            artifact_id: string;
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "missing" | "mismatch" | "external" | "unsafe_path" | "unreadable";
        };
        /** ArtifactCheckCounts */
        ArtifactCheckCounts: {
            /** External Count */
            external_count: number;
            /** Mismatch Count */
            mismatch_count: number;
            /** Missing Count */
            missing_count: number;
            /** Unreadable Count */
            unreadable_count: number;
            /** Unsafe Path Count */
            unsafe_path_count: number;
            /** Verified Count */
            verified_count: number;
        };
        /** AvailableArtifact */
        AvailableArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Content Digest */
            content_digest: string;
            /** Created By Stage */
            created_by_stage: string;
            /** Media Type */
            media_type: string;
            /** Original Name */
            original_name: string;
            /** Path Or Uri */
            path_or_uri: string;
            /**
             * Role
             * @enum {string}
             */
            role: "receptor_input" | "ligand_input" | "predicted_complex" | "pose_set" | "raw_score_output" | "validation_output" | "interaction_output" | "log" | "report" | "other";
            semantic: components["schemas"]["SemanticArtifactSummary"] | null;
            /** Size Bytes */
            size_bytes: number;
            /** Source Metadata */
            source_metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            verification: components["schemas"]["ArtifactCheck"];
        };
        /** BinderProbabilityPrediction */
        BinderProbabilityPrediction: {
            /** Caveats */
            caveats: string[];
            /** Id */
            id: string;
            /** Interpretation */
            interpretation: string;
            /** Method Id */
            method_id: string;
            /**
             * Optimization Direction
             * @default higher_is_better
             * @constant
             */
            optimization_direction: "higher_is_better";
            raw_source: components["schemas"]["PredictionRawSource"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "complex" | "pose" | "ligand" | "residue" | "atom";
            /** Scope Id */
            scope_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binder_probability";
            uncertainty: components["schemas"]["PredictionUncertainty"] | null;
            /**
             * Unit
             * @default probability
             * @constant
             */
            unit: "probability";
            /** Value */
            value: number;
        };
        /** Body_import_evidence_bundle */
        Body_import_evidence_bundle: {
            /**
             * Bundle
             * @description Portable Molecule Atlas evidence bundle ZIP
             */
            bundle: string;
        };
        /** CandidateEvidenceBinding */
        CandidateEvidenceBinding: {
            /** Candidate External Id */
            candidate_external_id: string | null;
            /** Candidate Id */
            candidate_id: string;
            /** Explanation */
            explanation: string;
            /** Matched Input Artifact Ids */
            matched_input_artifact_ids: string[];
            /** Matched Input Ids */
            matched_input_ids: string[];
            /** Reference Ids Checked */
            reference_ids_checked: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "bound" | "unbound" | "ambiguous";
        };
        /** CandidateEvidenceWarning */
        CandidateEvidenceWarning: {
            /**
             * Code
             * @enum {string}
             */
            code: "candidate_not_bound" | "ambiguous_candidate_binding" | "semantic_lineage_unavailable" | "prediction_limit_reached" | "validation_limit_reached";
            /** Message */
            message: string;
        };
        /** CandidateSet */
        CandidateSet: {
            /** Candidates */
            candidates: (components["schemas"]["ValidCandidate"] | components["schemas"]["InvalidCandidate"])[];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CompareCandidatesInput */
        CompareCandidatesInput: {
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Subjects */
            subjects: components["schemas"]["ComparisonSubjectInput"][];
        };
        /** CompareCandidatesOutput */
        CompareCandidatesOutput: {
            /**
             * Capability Id
             * @default compare_candidates
             * @constant
             */
            capability_id: "compare_candidates";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Excluded Prediction Count */
            excluded_prediction_count: number;
            /** Prediction Groups */
            prediction_groups: components["schemas"]["PredictionComparisonGroup"][];
            /** Subjects */
            subjects: components["schemas"]["ComparisonSubjectResult"][];
            /** Warnings */
            warnings: components["schemas"]["ComparisonWarning"][];
        };
        /** ComparisonPredictionEntry */
        ComparisonPredictionEntry: {
            /** Candidate Id */
            candidate_id: string;
            /** Prediction */
            prediction: components["schemas"]["DockingEnergyPrediction"] | components["schemas"]["PoseConfidencePrediction"] | components["schemas"]["StructureConfidencePrediction"] | components["schemas"]["BinderProbabilityPrediction"] | components["schemas"]["PredictedAffinityPrediction"];
            /** Run Id */
            run_id: string;
            /** Subject Id */
            subject_id: string;
        };
        /** ComparisonSubjectInput */
        ComparisonSubjectInput: {
            /** Candidate External Id */
            candidate_external_id?: string | null;
            /** Candidate Id */
            candidate_id: string;
            /** Label */
            label: string;
            /** Run Id */
            run_id: string;
            /** Subject Id */
            subject_id: string;
        };
        /** ComparisonSubjectResult */
        ComparisonSubjectResult: {
            binding: components["schemas"]["CandidateEvidenceBinding"];
            /** Candidate External Id */
            candidate_external_id: string | null;
            /** Candidate Id */
            candidate_id: string;
            /** Label */
            label: string;
            method: components["schemas"]["MethodSummary"];
            /** Related Artifact Ids */
            related_artifact_ids: string[];
            /** Run Id */
            run_id: string;
            /** Subject Id */
            subject_id: string;
            validation_counts: components["schemas"]["ValidationCounts"];
        };
        /** ComparisonWarning */
        ComparisonWarning: {
            /**
             * Code
             * @enum {string}
             */
            code: "comparison_subject_unbound" | "comparison_subject_ambiguous" | "no_shared_prediction_groups";
            /** Message */
            message: string;
            /** Subject Id */
            subject_id?: string | null;
        };
        /** ConformerResponse */
        ConformerResponse: {
            /** Candidate Id */
            candidate_id: string;
            /** Mol Block */
            mol_block: string;
        };
        /** DescriptorSet */
        DescriptorSet: {
            /** Fraction Csp3 */
            fraction_csp3: number;
            /** Hbond Acceptors */
            hbond_acceptors: number;
            /** Hbond Donors */
            hbond_donors: number;
            /** Heavy Atom Count */
            heavy_atom_count: number;
            /** Logp */
            logp: number;
            /** Molecular Weight */
            molecular_weight: number;
            /** Murcko Scaffold */
            murcko_scaffold: string | null;
            /** Ring Count */
            ring_count: number;
            /** Rotatable Bonds */
            rotatable_bonds: number;
            /** Tpsa */
            tpsa: number;
        };
        /** DockingEnergyPrediction */
        DockingEnergyPrediction: {
            /** Caveats */
            caveats: string[];
            /** Id */
            id: string;
            /** Interpretation */
            interpretation: string;
            /** Method Id */
            method_id: string;
            /**
             * Optimization Direction
             * @default lower_is_better
             * @constant
             */
            optimization_direction: "lower_is_better";
            raw_source: components["schemas"]["PredictionRawSource"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "complex" | "pose" | "ligand" | "residue" | "atom";
            /** Scope Id */
            scope_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "docking_energy";
            uncertainty: components["schemas"]["PredictionUncertainty"] | null;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** GenerateEvidenceReportOutput */
        GenerateEvidenceReportOutput: {
            /**
             * Capability Id
             * @default generate_evidence_report
             * @constant
             */
            capability_id: "generate_evidence_report";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /** Content */
            content: string;
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /**
             * Report Format
             * @enum {string}
             */
            report_format: "markdown" | "html";
            /** Run Id */
            run_id: string;
        };
        /** GetCandidateEvidenceOutput */
        GetCandidateEvidenceOutput: {
            binding: components["schemas"]["CandidateEvidenceBinding"];
            /**
             * Capability Id
             * @default get_candidate_evidence
             * @constant
             */
            capability_id: "get_candidate_evidence";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Lineage Available */
            lineage_available: boolean;
            method: components["schemas"]["MethodSummary"];
            /** Prediction Limit */
            prediction_limit: number;
            /** Prediction Total */
            prediction_total: number;
            /** Predictions */
            predictions: (components["schemas"]["DockingEnergyPrediction"] | components["schemas"]["PoseConfidencePrediction"] | components["schemas"]["StructureConfidencePrediction"] | components["schemas"]["BinderProbabilityPrediction"] | components["schemas"]["PredictedAffinityPrediction"])[];
            /** Related Artifact Ids */
            related_artifact_ids: string[];
            /** Run Id */
            run_id: string;
            /** Validation Limit */
            validation_limit: number;
            /** Validation Results */
            validation_results: components["schemas"]["ValidationResult"][];
            /** Validation Total */
            validation_total: number;
            /** Warnings */
            warnings: components["schemas"]["CandidateEvidenceWarning"][];
        };
        /** GetRunSummaryOutput */
        GetRunSummaryOutput: {
            /**
             * Capability Id
             * @default get_run_summary
             * @constant
             */
            capability_id: "get_run_summary";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            run: components["schemas"]["RunSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ImportEvidenceBundleOutput */
        ImportEvidenceBundleOutput: {
            /**
             * Capability Id
             * @default import_evidence_bundle
             * @constant
             */
            capability_id: "import_evidence_bundle";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Idempotency Replayed */
            idempotency_replayed: boolean;
            run: components["schemas"]["RunSummary"];
        };
        /** InvalidCandidate */
        InvalidCandidate: {
            /** Canonical Smiles */
            canonical_smiles?: null;
            /** Descriptors */
            descriptors?: null;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default false
             * @constant
             */
            is_valid: false;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "invalid";
            /** Structure Svg */
            structure_svg?: null;
            /** Target */
            target?: string | null;
            /** Triage Flags */
            triage_flags?: null;
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        JsonValue: unknown;
        /** LigandInputSummary */
        LigandInputSummary: {
            /** Artifact Id */
            artifact_id: string;
            /** Input Id */
            input_id: string;
            /** Representation */
            representation: string | null;
            /** Upstream Id */
            upstream_id: string | null;
        };
        /** ListAvailableArtifactsOutput */
        ListAvailableArtifactsOutput: {
            /** Artifacts */
            artifacts: components["schemas"]["AvailableArtifact"][];
            /**
             * Capability Id
             * @default list_available_artifacts
             * @constant
             */
            capability_id: "list_available_artifacts";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Run Id */
            run_id: string;
            /** Total */
            total: number;
        };
        /** ListEvidenceRunsOutput */
        ListEvidenceRunsOutput: {
            /**
             * Capability Id
             * @default list_evidence_runs
             * @constant
             */
            capability_id: "list_evidence_runs";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
        };
        /** ManifestWarning */
        ManifestWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /** MethodSummary */
        MethodSummary: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            /** Checkpoint Id */
            checkpoint_id: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256: string | null;
            /** Command */
            command: string[];
            /** Container Digest */
            container_digest: string | null;
            /** Container Image */
            container_image: string | null;
            /** Method Id */
            method_id: string;
            /** Random Seeds */
            random_seeds: number[];
            /** Source Commit */
            source_commit: string | null;
            /** Upstream Tool */
            upstream_tool: string | null;
            /** Upstream Version */
            upstream_version: string | null;
        };
        /** PoseConfidencePrediction */
        PoseConfidencePrediction: {
            /** Caveats */
            caveats: string[];
            /** Id */
            id: string;
            /** Interpretation */
            interpretation: string;
            /** Method Id */
            method_id: string;
            /**
             * Optimization Direction
             * @default higher_is_better
             * @constant
             */
            optimization_direction: "higher_is_better";
            raw_source: components["schemas"]["PredictionRawSource"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "complex" | "pose" | "ligand" | "residue" | "atom";
            /** Scope Id */
            scope_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pose_confidence";
            uncertainty: components["schemas"]["PredictionUncertainty"] | null;
            /** Unit */
            unit?: null;
            /** Value */
            value: number;
        };
        /** PredictedAffinityPrediction */
        PredictedAffinityPrediction: {
            /** Caveats */
            caveats: string[];
            /** Id */
            id: string;
            /** Interpretation */
            interpretation: string;
            /** Method Id */
            method_id: string;
            /**
             * Optimization Direction
             * @enum {string}
             */
            optimization_direction: "lower_is_better" | "higher_is_better";
            raw_source: components["schemas"]["PredictionRawSource"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "complex" | "pose" | "ligand" | "residue" | "atom";
            /** Scope Id */
            scope_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "predicted_affinity";
            uncertainty: components["schemas"]["PredictionUncertainty"] | null;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** PredictionComparisonGroup */
        PredictionComparisonGroup: {
            /** Entries */
            entries: components["schemas"]["ComparisonPredictionEntry"][];
            /**
             * Optimization Direction
             * @enum {string}
             */
            optimization_direction: "lower_is_better" | "higher_is_better" | "none";
            /**
             * Prediction Type
             * @enum {string}
             */
            prediction_type: "docking_energy" | "pose_confidence" | "structure_confidence" | "binder_probability" | "predicted_affinity";
            /** Unit */
            unit: string | null;
        };
        /** PredictionRawSource */
        PredictionRawSource: {
            /** Artifact Id */
            artifact_id: string;
            /** Field */
            field: string;
            /** Upstream Record Id */
            upstream_record_id?: string | null;
        };
        /** PredictionUncertainty */
        PredictionUncertainty: {
            /** Kind */
            kind: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value: number;
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RunFailure */
        RunFailure: {
            /** Category */
            category: string;
            /** Details */
            details: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Exit Code */
            exit_code?: number | null;
            /** Message */
            message: string;
            /** Stage */
            stage?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Artifact Count */
            artifact_count: number;
            /** Expected Outputs */
            expected_outputs: string[];
            failure: components["schemas"]["RunFailure"] | null;
            /** Finished At */
            finished_at: string | null;
            /** Ligand Inputs */
            ligand_inputs: components["schemas"]["LigandInputSummary"][];
            method: components["schemas"]["MethodSummary"];
            /** Missing Outputs */
            missing_outputs: string[];
            /** Prediction Count */
            prediction_count: number;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "succeeded" | "failed" | "partial" | "cancelled" | "unknown";
            validation_counts: components["schemas"]["ValidationCounts"];
            /** Warnings */
            warnings: components["schemas"]["ManifestWarning"][];
        };
        /** SemanticArtifactSummary */
        SemanticArtifactSummary: {
            /**
             * Artifact Type
             * @enum {string}
             */
            artifact_type: "model-input" | "ligand-structure" | "protein-structure" | "predicted-complex" | "docking-pose-set" | "raw-prediction-output" | "validation-report" | "run-log" | "evidence-report";
            /** Derived From Artifact Ids */
            derived_from_artifact_ids: string[];
            /** Domain Metadata */
            domain_metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Logical Name */
            logical_name: string;
            /** Preview Metadata */
            preview_metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Schema Version */
            schema_version: string | null;
            /**
             * Semantic Role
             * @enum {string}
             */
            semantic_role: "input" | "primary_output" | "raw_output" | "normalized_output" | "validation_output" | "log" | "report";
        };
        /** SimilarityNeighbor */
        SimilarityNeighbor: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** Similarity */
            similarity: number;
        };
        /** StructureConfidencePrediction */
        StructureConfidencePrediction: {
            /** Caveats */
            caveats: string[];
            /** Id */
            id: string;
            /** Interpretation */
            interpretation: string;
            /** Method Id */
            method_id: string;
            /**
             * Optimization Direction
             * @default higher_is_better
             * @constant
             */
            optimization_direction: "higher_is_better";
            raw_source: components["schemas"]["PredictionRawSource"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "complex" | "pose" | "ligand" | "residue" | "atom";
            /** Scope Id */
            scope_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "structure_confidence";
            uncertainty: components["schemas"]["PredictionUncertainty"] | null;
            /** Unit */
            unit?: null;
            /** Value */
            value: number;
        };
        /** TriageFlags */
        TriageFlags: {
            /** Lipinski Notes */
            lipinski_notes: string[];
            /** Lipinski Violations */
            lipinski_violations: number;
            /** Veber Notes */
            veber_notes: string[];
            /** Veber Violations */
            veber_violations: number;
        };
        /** ValidCandidate */
        ValidCandidate: {
            /** Canonical Smiles */
            canonical_smiles: string;
            descriptors: components["schemas"]["DescriptorSet"];
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Valid
             * @default true
             * @constant
             */
            is_valid: true;
            /** Name */
            name: string;
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["SimilarityNeighbor"][];
            /** Notes */
            notes?: string | null;
            /** Score */
            score?: number | null;
            /** Smiles */
            smiles: string;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "valid";
            /** Structure Svg */
            structure_svg: string;
            /** Target */
            target?: string | null;
            triage_flags: components["schemas"]["TriageFlags"];
            /** Validation Notes */
            validation_notes: components["schemas"]["ValidationNote"][];
        };
        /** ValidateEvidenceArtifactsOutput */
        ValidateEvidenceArtifactsOutput: {
            /** Artifact Checks */
            artifact_checks: components["schemas"]["ArtifactCheck"][];
            /**
             * Capability Id
             * @default validate_evidence_artifacts
             * @constant
             */
            capability_id: "validate_evidence_artifacts";
            /**
             * Capability Version
             * @default 0.1.0
             * @constant
             */
            capability_version: "0.1.0";
            /**
             * Contract Version
             * @default 0.1.0
             * @constant
             */
            contract_version: "0.1.0";
            /** Correlation Id */
            correlation_id: string;
            counts: components["schemas"]["ArtifactCheckCounts"];
            /** Run Id */
            run_id: string;
            /** Warnings */
            warnings: components["schemas"]["ManifestWarning"][];
        };
        /** ValidationCounts */
        ValidationCounts: {
            /** Error Count */
            error_count: number;
            /** Fail Count */
            fail_count: number;
            /** Pass Count */
            pass_count: number;
            /** Unavailable Count */
            unavailable_count: number;
            /** Warning Count */
            warning_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationNote */
        ValidationNote: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Check Id */
            check_id: string;
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /** Input Artifact Id */
            input_artifact_id: string;
            /** Measured Value */
            measured_value: boolean | number | string | null;
            /** Raw Output Artifact Id */
            raw_output_artifact_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "warning" | "unavailable" | "error";
            /** Threshold Or Configuration */
            threshold_or_configuration: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Unit */
            unit?: string | null;
            /** Validator */
            validator: string;
            /** Validator Version */
            validator_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_candidate_set_api_candidate_sets_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSet"];
                };
            };
        };
    };
    get_candidate_conformer_api_candidate_sets_demo_candidates__candidate_id__conformer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConformerResponse"];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conformer cannot be generated */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stored candidate data is inconsistent */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candidate_neighbors_api_candidate_sets_demo_candidates__candidate_id__neighbors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityNeighbor"][];
                };
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_projection_api_candidate_sets_demo_projection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionPoint"][];
                };
            };
        };
    };
    compare_candidates: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareCandidatesInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareCandidatesOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_evidence_bundle: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Correlation-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_evidence_bundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportEvidenceBundleOutput"];
                };
            };
            /** @description Unsafe or invalid evidence bundle */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Import conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Evidence bundle limit exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_runs: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEvidenceRunsOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_summary: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRunSummaryOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_evidence_artifacts: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateEvidenceArtifactsOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_artifacts: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAvailableArtifactsOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_evidence: {
        parameters: {
            query?: {
                candidate_external_id?: string | null;
                prediction_limit?: number;
                validation_limit?: number;
            };
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCandidateEvidenceOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_evidence_report: {
        parameters: {
            query?: {
                report_format?: "markdown" | "html";
            };
            header?: {
                "X-Correlation-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateEvidenceReportOutput"];
                };
            };
            /** @description Evidence run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
