from .cDataStructs import ExplicitBitVect

def ConvertToNumpyArray(vector: ExplicitBitVect, array: object) -> None: ...
def TanimotoSimilarity(left: ExplicitBitVect, right: ExplicitBitVect) -> float: ...
